### PR TITLE
add quay.io to the repos we sub with 'registry' config

### PR DESCRIPTION
**Pull request by kwmonroe**
Backport #103 to 1.15

### CODE REVIEW

**Comment by Cynerva** [comment]
This looks fine, but I don't think the release-1.15 branch is supposed to exist yet. I'm pretty sure we had automation set up to create a release-1.x branch the first time there is a stable 1.x release. There is no stable 1.15 yet. Did something change?

**Comment by hyperbolic2346** [comment]
Are we creating the branch once we start building betas for a release?

**Comment by Cynerva** [comment]
> Are we creating the branch once we start building betas for a release?

Alphas. We discussed this on IRC. The new cdk-addons job creates the release-1.x branch the first time a cdk-addons snap is built for 1.x (alpha, beta or otherwise) [here](https://github.com/charmed-kubernetes/jenkins/blob/f6f32b388aff8847daa0c649cf78d09cb02847d0/jobs/build-snaps/build-release-cdk-addons.groovy#L42-L52). Before, the release branch wasn't created until we promoted a snap to 1.x/stable [here](https://github.com/charmed-kubernetes/jenkins/blob/f6f32b388aff8847daa0c649cf78d09cb02847d0/jobs/build-snaps/promote.sh#L43-L44).

**Comment by kwmonroe** [comment]
Just a heads up, I've deleted `release-1.15`. The cdk addons job is now setup so it only creates this branch once stable-1.15.txt exists upstream:

https://github.com/charmed-kubernetes/jenkins/pull/413

**Pull request merged**
