### PR TITLE
Adding kube-state-metrics

### PR DESCRIPTION
**Pull request by hyperbolic2346**
Deployed when enable-metrics is set to true.

### CODE REVIEW

**Comment by Cynerva** [comment]
Link to bug?

**Comment by Cynerva** [comment]
I've seen cases where the user experience with `enable-dashboard-addons` suffers because the config is too broad. The user wants to customize something in grafana, but that requires them to set `enable-dashboard-addons=false` and then manually deploy grafana, heapster, and kubernetes-dashboard.

Having said that, do you think it's worthwhile to give kube-state-metrics its own `enable-kube-state-metrics` config, rather than grouping it in with the metrics server in `enable-metrics`?

**Comment by hyperbolic2346** [comment]
I wor

> I've seen cases where the user experience with `enable-dashboard-addons` suffers because the config is too broad. The user wants to customize something in grafana, but that requires them to set `enable-dashboard-addons=false` and then manually deploy grafana, heapster, and kubernetes-dashboard.

I think the general plan here is to wait for CaaS charms, but I get it. This will mean disabling metrics requires one more thing to deploy. Do we have docs for that somewhere now that should be updated?

> Having said that, do you think it's worthwhile to give kube-state-metrics its own `enable-kube-state-metrics` config, rather than grouping it in with the metrics server in `enable-metrics`?

I don't, because I can't imagine a time when you'd want to enable one instead of the other. It seems that if you want metrics enabled, you'd want to see the node metrics and the workload metrics. I'm willing to be persuaded though if you feel strongly about it.

**Comment by Cynerva** [comment]
> Do we have docs for that somewhere now that should be updated?

Not that I'm aware of.

> I'm willing to be persuaded though if you feel strongly about it.

Nah, not really. Thanks for considering it.

**Comment by hyperbolic2346** [comment]
https://bugs.launchpad.net/charmed-kubernetes-bundles/+bug/1850710

**Comment by Cynerva** [comment]
LGTM :+1: Code looks good. I did a test build and verified that the templates included in the snap look reasonable. I verified that the Deployment has the correct substitution to support the `registry` config. I also verified that `make upstream-images` includes the kube-state-metrics image as it should.

One concern I had is that this doesn't appear to support arm64 and s390x. However, as far as I can tell, upstream doesn't release images for those architectures, and we don't support metrics-server on those architectures anyway. So we should be OK to ignore that concern for now.

@hyperbolic2346, I'd merge this but I don't know if it's been tested in a deployment of Charmed Kubernetes. If you have tested that, then feel free to merge this.

**Comment by hyperbolic2346** [comment]
Sorry, I forgot to mention that this was tested on AWS in CK for Kubernetes 1.16. I related to a LMA deployment and was able to see the new metrics being reported into prometheus and make graphs with the data in grafana.

**Comment by hyperbolic2346** [comment]
I think this needs some cleanup. Don't merge it yet. I can automate some more of this.

**Comment by hyperbolic2346** [comment]
Added https://github.com/charmed-kubernetes/charm-kubernetes-master/pull/69 to address the automation.

**Pull request merged**
