### PR TITLE
add workaround for registries that do not support multi-arch images

### PR DESCRIPTION
**Pull request by kwmonroe**
Partial fix for https://github.com/charmed-kubernetes/jenkins/issues/445.  The rest will happen on the jenkins side, when images are actually pushed to the canonical registry.

### CODE REVIEW

**Comment by kwmonroe** [comment]
Locally built snap with this seems ok:

```bash
## current 1.15/stable snap:
root@ip-172-31-12-198:~/snap/cdk-addons# cat current/addons/core-dns.yaml |grep image:
        image: image-registry.canonical.com:5000/cdk/coredns/coredns:1.4.0

## install locally built snap and wait for hooks to run; see the {{multiarch_workaround}} in the image name
root@ip-172-31-12-198:~/snap/cdk-addons# cat current/addons/core-dns.yaml |grep image:
        image: image-registry.canonical.com:5000/cdk/coredns/coredns-amd64:1.5.1
```

**Comment by Cynerva** [comment]
I hate it. LGTM.

I have reservations. This looks like a good quick fix, but I can easily see it leading to long-term confusion. When someone installs CDK, they'll see it pulling images from image-registry.canonical.com. If they later come along with an offline deployment, they might think they can mirror the images from image-registry.canonical.com to their offline registry, configure image-registry=my.local.registry, and have it work. But it won't, because in one case the image is "coredns", while in the other it's "coredns-amd64". That's confusing.

But, as we discussed this morning, image-registry.canonical.com is not configured to host fat manifests. So we don't have much of a choice.

@kwmonroe, if I have any concern that's blocking, it's that the offline registry case does not also include the -arch suffix. As it is now, with this PR, the offline registry case will behave more like the `image-registry=""` case (which is abnormal) than the `image-registry=image-registry.canonical.com:5000/cdk` case (which has become our new baseline). I would rather standardize on the names we use in image-registry.canonical.com, and let docker.io and friends be the exception instead. What do you think?

**Comment by kwmonroe** [comment]
> If they later come along with an offline deployment, they might think they can mirror the images from image-registry.canonical.com to their offline registry

I see your point, but I don't think people will do this.  It's pretty difficult to figure out every image we host for CDK in i-r-c.c and then mirror those in a separate registry.  I think it's more likely people will populate their registry from the [container images](https://github.com/charmed-kubernetes/bundle/blob/master/container-images.txt) doc, which only lists upstream images.

> the offline registry case does not also include the -arch suffix.

Per above, I think this is a good thing as I suspect offline registry owners will populate with upstream images.

> I would rather standardize on the names we use in image-registry.canonical.com, and let docker.io and friends be the exception instead. What do you think?

I hate it :)  I think we should set our long term goal to match upstream names.  That is, make i-r.c.c support multi arch manifests and drop this wacky workaround.  I've opened the following to track this enablement:

https://bugs.launchpad.net/layer-docker-registry/+bug/1835266

I've also opened a doc issue to beef up the private registry page.  We can explicitly tell people to use the upstream images and hopefully they'll never know we ever had an `-$arch` suffix workaround:

https://github.com/charmed-kubernetes/kubernetes-docs/issues/237

**Comment by Cynerva** [comment]
> I think we should set our long term goal to match upstream names. That is, make i-r.c.c support multi arch manifests and drop this wacky workaround.

OK, yeah, that's a good point. Taking this perspective, it does make sense to minimize the scope of the workaround.

Also, to be clear, when I said "I hate it", I meant I hate that we have to do this, not that I hate anything about how you've handled it. Sorry - realizing now that that came out more harsh and less funny than I intended.

One last thing that just crossed my mind. Does kube-dns need this workaround as well? IIRC, @joedborg was seeing problems with that on alt architectures too.

**Comment by kwmonroe** [comment]
I know it's not pretty, but i want to get this into `master` before we get too far along in 1.16 testing.

**Pull request merged**
