### PR TITLE
Updates for 1.16

### PR DESCRIPTION
**Pull request by hyperbolic2346**
Added a patch function to update the api version. It also adds in the selector since apps/v1 requires it. I kept the list as small as possible to try and prevent inadvertent issues.

### CODE REVIEW

**Comment by hyperbolic2346** [comment]
https://bugs.launchpad.net/cdk-addons/+bug/1841674

**Comment by Cynerva** [comment]
LGTM. I built a v1.16.0-beta.1 snap with this and verified that the modified templates look correct - the apiVersion and selector fields are the only things that changed, and the selectors match the labels of the pod templates. I also grepped the templates for extensions/v1beta1, apps/v1beta1, and apps/v1beta2 and didn't see any others that were missed.

It's not clear to me if you've tested this, but if you have, feel free to merge it.

**Comment by hyperbolic2346** [comment]
I have tested this. I verified that 1.16 failed before and works now.

**Comment by Cynerva** [comment]
Good enough for me :+1: Thanks @hyperbolic2346

**Pull request merged**
