### PR TITLE
Fixing template filename

### PR DESCRIPTION
**Pull request by hyperbolic2346**
Template name is gce, not gcp.

### CODE REVIEW

**Comment by tvansteenburgh** [comment]
Since the flag is 'enable-gcp', I think it'd be better to rename the file instead (to storageclass-gcp.yaml). So things are consistently 'gcp', not one of each. Also, please open an LP bug for this. PITA I know, but without it we may forget to backport this fix, if that's necessary? Do we need to backport? I didn't look to see when this bug was introduced.

**Comment by hyperbolic2346** [comment]
@tvansteenburgh The problem there is that inside the template is all gce and the provisioner is gce, so it seems like we should convert everything to gce. I was going to just groan and let it slide, but I'm happy to go through the conversion if that's what you want.

**Comment by hyperbolic2346** [comment]
https://bugs.launchpad.net/cdk-addons/+bug/1851736

**Comment by Cynerva** [comment]
Inconsistency is annoying, but when it's this widespread -- where we have the gcp-integrator charm on one hand, and the StorageClass's kubernetes.io/gce-pd provisioner on the other hand -- it's just too much work, and too much risk, to make it all consistent.

Thanks for the fix. LGTM

**Pull request merged**
