### PR TITLE
Fixing yaml.load deprecation.

### PR DESCRIPTION
**Pull request by hyperbolic2346**
See https://bugs.launchpad.net/charm-kubernetes-master/+bug/1822020

### CODE REVIEW

**Comment by battlemidget** [comment]
I think using the `safe_xxx` methods work as well, not sure that matters here just a fyi

**Comment by hyperbolic2346** [comment]
We're apparently using python2 still for these, so this doesn't display the deprecation warning and it actually breaks cdk-addons since FullLoader doesn't exist.

**Comment by Cynerva** [comment]
> We're apparently using python2 still for these

What? We shouldn't be. Python3 is right there in the shebangs. Where are we using python2?

**Comment by hyperbolic2346** [comment]
@Cynerva my personal make was broken with this and then when I changed the calls in the get_addon_templates code and deployed it the code blew up on the masters complaining that FullLoader couldn't be found as well. My assumption is that it was python2, but that may be incorrect. I'm not sure why it wouldn't be found otherwise though.

**Comment by Cynerva** [comment]
Ah, okay. That'd be a difference in PyYAML version.

**Comment by battlemidget** [comment]
Just use safe_* and be done with it

**Pull request closed without merging**
